language: python
python:
    - "3.6.4"

stages:
  - lint
  - test
  - type

install:
    - pip install -r requirements-dev.txt

jobs:
    include:
        - stage: lint
          script: tox -e lint
        - stage: type
          script: tox -e type
        - stage: test
          script: tox -e test


after_success:
    coveralls
