language: python
python:
    - "3.6"

stages:
    - lint
    - test
    - type

install:
    - pip install pipenv
    - pipenv install --dev

jobs:
    include:
        - stage: lint
          script: tox -e lint
        - stage: type
          script: tox -e type
        - stage: test
          script: tox -e test


after_success:
    coveralls
