language: python
python:
    - "3.6"

stages:
    - lint
    - type
    - test


install:
    - pip install pipenv
    - pipenv install --dev

jobs:
    include:
        - stage: lint
          script: pipenv run tox -e lint
        - stage: type
          script: pipenv run tox -e type
        - stage: test
          script: pipenv run tox -e test


after_success:
    pipenv run coveralls
