language: python
python:
  - "3.6"

stages:
  - lint
  - type
  - tests


install:
  - pip install pipenv
  - make install-dev

jobs:
  include:
    - stage: lint
      script: make lint
    - stage: type
      script: make type
    - stage: tests
      script: make tests


after_success:
  pipenv run coveralls
