language: python
python:
  - '3.6'

stages:
  - lint
  - type
  - test
  - deploy

install:
  - pip install pipenv
  - make install-dev

jobs:
  include:
    - stage: lint
      script: make lint
    - stage: type
      script: make type
    - stage: test
      script: make tests
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: matthieugouel
        distributions: sdist bdist_wheel
        password:
          secure: vhpseb91lZ+e7JCaH+DN316aEx1dxk1QZcYibBvis9/PyKFnDD85MqOQVE0Gco+Duo3IPyaCkPflJO2KvXqcG48rP+ZgcF9w9dRR4k+pHv6/I5LuoWr8wGENe/A2xxT9KKs1ggSPgsynZuDPUeSk3NHy+t5OTLM+efA1W2rPUzwa6UewNsGLTz6sD0EgSZtxY6yQqv4nZdTqQ/17tTGWGqWM5qEiOaTsVv8u9gXa2NjbBcBznp5W+ZuYIZH+lSwwGhwQ+UWojlQp4rjUzqsZk0a8KOTUWAAPMzattZ3qN/Nl0K03jUSVntcRMOMddzOPcU73RODje8i51RAYqHo7jE+wv5z197fScwjwQ1DrnCVUqaz7vUEB8m31m3rC9952l8gcZ/5xiB8E/368qGodr9lxeutl83ck+YMXLfyLqPLXf2yBdzRkhWxsda9G2kH6BCLvnubVDVoWP+Ce0txjenbKhdX2l3K3ZP8bOlVT5hLuKNP9gZ0YkPd3R9YNFAzkDmiMyIxauBiBqskxePm2XvD0FiX0I9BGvSRqB+fMuioWhNylpUM9CuH9VH/UhSXI8YYCkp7Y06tjk/lHwEU70seS5wc2fSUA5YWL59figHBSn4Pd0mQ/zWT7eSxtePWCAy6ir9TwrrJOa7394PHxycuLCweRzQXmkOZHZCguLoc=
        on:
          tags: true
      if: tag IS present

after_success:
  pipenv run coveralls
